### ISSUE TITLE
why mention a modified toml file

### ISSUE THREAD

**Issue by tshepang** [biluohc/app#2]
In README, we have this line:

> Run cargo doc --open after modified the toml file.

I don't understand why the toml file is mentioned, so maybe it needs some explanation.

**Comment by biluohc** [comment]
# I give your a example.

## `cargo new --bin name`    
     Created binary (application) `name` project

## `tree name/`
name/
├── Cargo.toml
└── src
    └── main.rs

## `cat name/Cargo.toml `
[package]
name = "name"
version = "0.1.0"
[dependencies]

## `echo  "app = \"0.5.6\"" >>name/Cargo.toml  ` 

### Add dependency to the toml file: `app = "0.5.6"`

### You could use other editor to modify the file

## `cat name/Cargo.toml `
[package]
name = "name"
version = "0.1.0"
[dependencies]
app = "0.5.6"

## `cd name/`
## `cargo doc --open`  #cargo will use your default brower open the Document
